# Generated by Django 5.0.1 on 2024-04-07 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVendasDiretas', '0004_remove_produto_url_fornecedor_site_produto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='alias',
            field=models.CharField(default=1, max_length=264, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCliente',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='idFornecedor',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idPedido',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='idProduto',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=0, max_length=264, unique=True),
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('idCiclo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ciclo', models.CharField(max_length=264, unique=True)),
                ('dataInicio', models.DateField(default=0)),
                ('dataFim', models.DateField(default=0)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVendasDiretas.fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciclo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appVendasDiretas.ciclo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetalheDoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVendasDiretas.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVendasDiretas.produto')),
            ],
        ),
    ]
